python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_100_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_200_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_400_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_500_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_1000_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_2000_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_4000_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_5000_2.json fr_home_connection.json

python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json
python remoterun.py tests/speedTest/frolov_heat_1_10000_2.json fr_home_connection.json